accessing
exception: anError

	exception := anError